### PR TITLE
updates readthedocs.txt fixes issue #11

### PR DESCRIPTION
**Pull request by codeblech**
#### fixed readthedocs documentation issue #11 
i ran the command `poetry export --with docs -f requirements.txt -o requirements-docs.txt` on the latest repo checkout. 
then i ran the build on readthedocs through my personal account, and [it worked](https://dbt-llm-tools-fork.readthedocs.io/en/latest/)

### CODE REVIEW

**Comment by pragunbhutani** [comment]
Thanks for the fix @codeblech!

Would you like to take this one step further and add a pre-commit hook that checks if the `pyproject.toml` file has changed and if so, regenerates the `requirements-docs.txt` file using the command you've mentioned?

We can also do that as a separate issue if you'd rather merge this first, I'm ok with either approach. Let me know!

**Comment by codeblech** [comment]
Ideally, I'd want to merge after setting up the githook. But, we don't currently have a hosted documentation. I believe we should merge as is, and open up a new issue. 
Either way, I'll coordinate with @ciaokitty and work on it

**Comment by pragunbhutani** [comment]
@codeblech in that case, can you please open an issue / enhancement to add a pre-commit hook so that we don't forget it? Then we can merge this one.

**Comment by codeblech** [comment]
i opened the issue #28 
you can add the enhancement label

**Review by pragunbhutani — APPROVED** [review]

**Review by pragunbhutani — APPROVED** [review]

**Pull request merged**
